### ISSUE TITLE
As a tester, I want to create a failing test, so that I can verify PR merge blocking for failed checks in GitHub

### ISSUE THREAD

**Issue by AR-RIFAT** [aodn/aodn-portal-v2#136]
## Acceptance Criteria

1. Complete tasks in task list

```[tasklist]
## Tasks
- [ ] Create a failing test
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1.

## Dependencies

1.

## Demo

1. Demo the result

**Comment by AR-RIFAT** [comment]
Since the demo is completed, it can now be closed.
