### ISSUE TITLE
As a tester, I want to update the test framework, so that I can test map functionalities

### ISSUE THREAD

**Issue by AR-RIFAT** [aodn/aodn-portal-v2#138]
## Acceptance Criteria

1. Complete tasks in task list

```[tasklist]
## Tasks
- [ ] Load map with `testMode: true` when env is dev
- [ ] Add a test to check map drag functionality
- [ ] Add a test to check functionality of hovering and clicking a datapoint
- [ ] Add a test to check that updating search reflects in map
- [ ] Add a test to check map base layers
- [ ] Add a test to check map spider
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1.

## Dependencies

1.

## Demo

1. Demo the result
