### ISSUE TITLE
As a tester, I want to add new ui tests for various features on the detail page

### ISSUE THREAD

**Issue by AR-RIFAT** [aodn/aodn-portal-v2#141]
## Acceptance Criteria

1. Complete tasks in task list

```[tasklist]
## Tasks
- [ ] Add tests for detail page functionalities
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## Demo

1. Demo the result

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
