### ISSUE TITLE
As a tester, I want to add new ui tests for sort, view & show more results features on the search page

### ISSUE THREAD

**Issue by AR-RIFAT** [aodn/aodn-portal-v2#189]
## Acceptance Criteria

1. Complete tasks in task list

```[tasklist]
## Tasks
- [x] Add test to check "Show more results" feature
- [x] Add test to check search sort and view related features
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## Demo

1. Demo the result
