### ISSUE TITLE
AS AN aodn developer I WANT to investigate the weird output SO THAT they are not confusing

### ISSUE THREAD

**Issue by HavierD** [aodn/aodn-portal-v2#195]
## Acceptance Criteria

1. solve the problem mentioned in task list
2. It is a low priority ticket.

## Notes

1. Currently, the playwright test output has error "Must provide a proper URL as target". (more information will put in comment). Could you please investigate it:

```[tasklist]
## Tasks
- [ ] Whether it is a big issue in ui test
- [ ] If this error output doesn't affect the playwright test, can we don't print them, or use warning instead of error
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1.

## Dependencies

1.

## Demo

1.

**Comment by HavierD** [comment]
VITE v5.4.8  ready in 346 ms
web-1    | 
web-1    |   ➜  Local:   http://localhost:5173/
web-1    |   ➜  Network: http://172.18.0.2:5173/
tests-1  | Server started successfully
tests-1  | ============================= test session starts ==============================
tests-1  | platform linux -- Python 3.10.12, pytest-8.2.2, pluggy-1.5.0
tests-1  | rootdir: /app
tests-1  | configfile: pytest.ini
tests-1  | plugins: metadata-3.1.1, html-4.1.1, base-url-2.1.0, xdist-3.6.1, playwright-0.4.4
tests-1  | collected 18 items
tests-1  | 
web-1    | 2:35:48 AM [vite] page reload playwright/reports/test-report.html
tests-1  | tests/detail_page/test_about_tab.py .                                    [  5%]
tests-1  | tests/detail_page/test_associated_records_tab.py .                       [ 11%]
tests-1  | tests/detail_page/test_citation_tab.py .                                 [ 16%]
web-1    | 2:36:26 AM [vite] http proxy error: Must provide a proper URL as target
web-1    | Error: Must provide a proper URL as target
web-1    |     at ProxyServer.<anonymous> (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61274:36)
web-1    |     at viteProxyMiddleware (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61605:15)
web-1    |     at call (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41320:7)
web-1    |     at next (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41264:5)
web-1    |     at viteCachedTransformMiddleware (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61738:5)
web-1    |     at call (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41320:7)
web-1    |     at next (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41264:5)
web-1    |     at cors (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41792:7)
web-1    |     at file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41828:17
web-1    |     at originCallback (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41818:15)
web-1    | 2:36:26 AM [vite] http proxy error: Must provide a proper URL as target
web-1    | Error: Must provide a proper URL as target
web-1    |     at ProxyServer.<anonymous> (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61274:36)
web-1    |     at viteProxyMiddleware (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61605:15)
web-1    |     at call (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41320:7)
web-1    |     at next (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41264:5)
web-1    |     at viteCachedTransformMiddleware (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61738:5)
web-1    |     at call (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41320:7)
web-1    |     at next (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41264:5)
web-1    |     at cors (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41792:7)
web-1    |     at file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41828:17
web-1    |     at originCallback (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41818:15)
web-1    | 2:36:29 AM [vite] http proxy error: Must provide a proper URL as target
web-1    | Error: Must provide a proper URL as target
web-1    |     at ProxyServer.<anonymous> (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61274:36)
web-1    |     at viteProxyMiddleware (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61605:15)
web-1    |     at call (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41320:7)
web-1    |     at next (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41264:5)
web-1    |     at viteCachedTransformMiddleware (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61738:5)
web-1    |     at call (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41320:7)
web-1    |     at next (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41264:5)
web-1    |     at cors (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41792:7)
web-1    |     at file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41828:17
web-1    |     at file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41828:17
web-1    |     at originCallback (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:41818:15)
tests-1  | tests/search/test_search.py ..                                           [100%]
tests-1  | 
tests-1  | =================================== FAILURES ===================================
tests-1  | _ test_map_spider[chromium-137.70--33.174-Integrated Marine Observing System (IMOS) - Location of assets-137.70--33.174] _
tests-1  | 
tests-1  | page_mock = <Page url='http://web:5173/search?isImosOnlyDataset=false&searchText=imos&polygon.type=Feature&polygon.bbox.0=137.6371...1145498504&polygon.geometry.coordinates.0.4.0=137.63717193603486&polygon.geometry.coordinates.0.4.1=-33.2153788544999'>
tests-1  | head_lng = '137.70', head_lat = '-33.174'
tests-1  | data_title = 'Integrated Marine Observing System (IMOS) - Location of assets'
tests-1  | data_lng = '137.70', data_lat = '-33.174'
tests-1  | 
tests-1  |     @pytest.mark.parametrize(
tests-1  |         'head_lng, head_lat, data_title, data_lng, data_lat',
tests-1  |         [
tests-1  |             (
tests-1  |                 '137.70',
tests-1  |                 '-33.174',
tests-1  |                 'Integrated Marine Observing System (IMOS) - Location of assets',
tests-1  |                 '137.70',
tests-1  |                 '-33.174',
tests-1  |             ),
tests-1  |         ],
tests-1  |     )
tests-1  |     def test_map_spider(
tests-1  |         page_mock: Page,
tests-1  |         head_lng: str,
tests-1  |         head_lat: str,
tests-1  |         data_title: str,
tests-1  |         data_lng: str,
tests-1  |         data_lat: str,
tests-1  |     ) -> None:
tests-1  |         landing_page = LandingPage(page_mock)
tests-1  |         search_page = SearchPage(page_mock)
tests-1  |     
tests-1  |         landing_page.load()
tests-1  |         landing_page.search.fill_search_text('imos')
tests-1  |         landing_page.search.click_search_button()
tests-1  |         search_page.wait_for_search_to_complete()
tests-1  |     
tests-1  |         search_page.map.center_map(head_lng, head_lat)
tests-1  |         page_mock.wait_for_timeout(1000)
tests-1  |     
tests-1  |         # Try to find and click a cluster
tests-1  |         cluster_found = execute_js(page_mock, 'findAndClickCluster')
tests-1  | >       assert cluster_found is True
tests-1  | E       assert False is True
tests-1  | 
tests-1  | tests/search/test_map.py:166: AssertionError
tests-1  | --------- Generated html report: file:///app/reports/test-report.html ----------
tests-1  | =========================== short test summary info ============================
tests-1  | FAILED tests/search/test_map.py::test_map_spider[chromium-137.70--33.174-Integrated Marine Observing System (IMOS) - Location of assets-137.70--33.174]
tests-1  | =================== 1 failed, 17 passed in 144.64s (0:02:24) ===================
web-1    | 2:38:12 AM [vite] page reload playwright/reports/test-report.html
Aborting on container exit...

tests-1 exited with code 1
 Container playwright-tests-1  Stopping
 Container playwright-tests-1  Stopped
 Container playwright-web-1  Stopping
 Container playwright-web-1  Stopped
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by AR-RIFAT** [comment]
@HavierD  If you run the web server without specifying a value for `VITE_API_HOST` in the `.env` file, these errors are shown when the website makes any API request. Similarly, in the GitHub workflow, there is no `.env` file, which results in errors. 

In UI tests, this should not be an issue, as all API requests are mocked.
