### ISSUE TITLE
As a tester, I want to add test to cover map move across page, so it works as expected

### ISSUE THREAD

**Issue by utas-raymondng** [aodn/aodn-portal-v2#207]
## Acceptance Criteria

1. Test case added

## Notes

1. Go to search page, drag and zoom the map
2. The url updated
3. Paste url to another tab, 
4. The map should zoom to and move to the same location (The cluster maybe a bit off which is expected)
5. Then select another of the result and go to detail page
6. Click the backward button and the same should restore the same position

```[tasklist]
## Tasks
- [ ] Add test case to cover this case
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1.

## Dependencies

1.

## Demo

1.
