### ISSUE TITLE
As a tester, I want to test the dropdown behavior so it looks good.

### ISSUE THREAD

**Issue by utas-raymondng** [aodn/aodn-portal-v2#209]
## Acceptance Criteria

1. Test cover this case

## Notes

1. When the menu shows, scroll the page and the meunitem flow on top
![image](https://github.com/user-attachments/assets/07ec5e1d-ce40-4855-a6e1-93e86832f7d3)
![image](https://github.com/user-attachments/assets/ad36227b-374b-4cf7-9ede-20fa20598ce9)

2. After the fix, the menuitem will stick to the select component, if the component is off screen, the menu item close

```[tasklist]
## Tasks
- [ ] Bug fix in https://github.com/aodn/aodn-portal-v2/pull/208, please kindly write playwright test to verify this.
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1. 

## Dependencies

1.

## Demo

1.

**Comment by AR-RIFAT** [comment]
The bugfix has been updated: now, when a dropdown opens, page scrolling will be disabled, and scrolling will re-enable once the dropdown options close. The Playwright test will verify this behavior by ensuring that scrolling is disabled when the dropdown is open and re-enabled after it closes.
