### ISSUE TITLE
Bug on run order

### ISSUE THREAD

**Issue by utas-raymondng** [aodn/aodn-portal-v2#218]
## Acceptance Criteria

1. Run test_map_state_persists_across_page  pass no matter it is running standalone or within the group

## Notes

1. Run the test_map.py, the test test_map_state_persists_across_page failed
2. Run test_map_state_persists_across_page alone pass

```[tasklist]
## Tasks
- [ ] Fix depends between test
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1.

## Dependencies

1.

## Demo

1.

**Comment by AR-RIFAT** [comment]
Fixed
