### ISSUE TITLE
AS A tester, I WANT to add a screenshot of the failing test to the test report SO THAT I can see the screen where the test failed directly from the test report.

### ISSUE THREAD

**Issue by AR-RIFAT** [aodn/aodn-portal-v2#220]
## Acceptance Criteria

1. The html report should contain a screenshot for failing tests.

```[tasklist]
## Tasks
- [ ] Add screenshot to the html report for failing tests.
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1.

## Dependencies

1.

## Demo

1. Demo the result
