### ISSUE TITLE
As a tester, I want to add new ui tests for search input, data link button and description 'Show All/Less'

### ISSUE THREAD

**Issue by AR-RIFAT** [aodn/aodn-portal-v2#227]
## Acceptance Criteria

1. Complete tasks in task list

```[tasklist]
## Tasks
- [ ] Add test to check that search input remains same after coming back to search page from the detail page.
- [ ] Add test to check that clicking the links button for a data item in the search results page should navigate to the detail page 'Links' tab.
- [ ] Add test to check the description 'Show All/Show Less' feature in the detail page.
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1.

## Dependencies

1.

## Demo

1. Demo the result
