### ISSUE TITLE
AS A AODN-Portal developer I WANT to check the UI tests after new feature SO THAT can pass the playwright test

### ISSUE THREAD

**Issue by NekoLyn** [aodn/aodn-portal-v2#244]
## Acceptance Criteria

1.playwright test pass

## Notes

1.please check the UI changes in the ticket https://github.com/aodn/backlog/issues/6059 (can find all the changes in 'demo' section)
![image](https://github.com/user-attachments/assets/39839e6a-2de5-423e-aa9e-ba995dbaea30)

```[tasklist]
## Tasks
- [ ] check the new features and pass the playwright tests that skipped
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs

1. https://github.com/aodn/aodn-portal-v2/pull/251
2. https://github.com/aodn/aodn-portal-v2/pull/258

## Dependencies

1.

## Demo

1.

**Comment by utas-raymondng** [comment]
The above PR fixed most of the skip, the map is still skip. @AR-RIFAT can you take a look? I believe it is due to some testid change

**Comment by AR-RIFAT** [comment]
@utas-raymondng I could not find any more skipped tests in the linked PR branch. Can you tell me the name of the test function that is skipped?

**Comment by utas-raymondng** [comment]
In the search_page/test_map.py

The first link 

pytestmark = pytest.mark.skip(reason="Temporarily skipping all search tests")

**Comment by utas-raymondng** [comment]
Item fixed so I close the issue, @NekoLyn please update your main
