### ISSUE TITLE
As a tester, I want to build the framework, so that I can start testing the frontend

### ISSUE THREAD

**Issue by utas-raymondng** [aodn/aodn-portal-v2#78]
## Acceptance Criteria
1. Complete tasks in task list

## Notes
1. The testing in github is run with docker container

```[tasklist]
## Tasks
- [ ] A mock server to handle UI http call, mimic ogcapi-java call, given a url call, it should return a predefined json read from a file.
- [ ] The test can be run in dev PC and build process, code can be merged iff test pass
- [ ] Update github action as needed.
- [ ] Write a test for the landing page targeting type in text box and suggestion popup.
- [ ] Clean up any AWS resources created during backlog work
- [ ] DOD [Link to checklist](https://www.notion.so/imos-world/Definition-of-Done-DoD-b98281f003a44ce890dfba5af2f00337)
```

## PRs
1. https://github.com/aodn/aodn-portal-v2/pull/127

## Dependencies
1.

## Demo
1. Demo the result
